#pragma once

#include <stdint.h>

enum ADC_COMMANDS {
    COMMAND_WAKEUP = 0x00,
    COMMAND_RDATA = 0x01,
    COMMAND_RDATAC = 0x03,
    COMMAND_SDATAC = 0x0F,
    COMMAND_RREG = 0x10,
    COMMAND_WREG = 0x50,
    COMMAND_SELFCAL = 0xF0,
    COMMAND_SELFOCAL = 0xF1,
    COMMAND_SELFGCAL = 0xF2,
    COMMAND_SYSOCAL = 0xF3,
    COMMAND_SYSGCAL = 0xF4,
    COMMAND_SYNC = 0xFC,
    COMMAND_STANDBY = 0xFD,
    COMMAND_RESET = 0xFE,
};